[package]
name = "hightower-cnet"
version = "0.1.0"
edition = "2024"

[dependencies]
hightower-client = "0.1.5"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
