[package]
name = "hightower-gateway"
version = "0.1.0"
edition = "2021"
authors = ["Chris Hayen <chris@shotgun.dev>"]
description = "Gateway service for the Hightower project"
license = "MIT"
repository = "https://github.com/chrishayen/hightower-gateway"
readme = "README.md"
keywords = ["gateway", "wireguard", "hightower"]
categories = ["network-programming"]

[lib]
name = "gateway"
path = "src/lib.rs"

[[bin]]
name = "hightower-gateway"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
ctrlc = "3"
hightower-wireguard = { version = "0.1.5", features = ["transport"] }
hightower-kv = "0.1.3"
hightower-naming = "0.1.3"
axum = "0.7"
tracing = "0.1"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"
subtle = "2"
tokio = { version = "1.47", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
rand = "0.8"
askama = "0.12"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tempfile = "3"

[dev-dependencies]
tempfile = "3"
