[package]
name = "hightower-kv"
version = "0.1.0"
edition = "2024"
authors = ["Chris Hayen"]
license = "MIT"
description = "Embedded log-structured key-value store with optional auth helpers"
readme = "README.md"
repository = "https://github.com/chrishayen/hightower-kv"
keywords = ["kv", "storage", "embedded", "log-structured"]
categories = ["database", "data-structures"]

[dependencies]
hashbrown = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
thiserror = "1.0"
argon2 = "0.5"
aes-gcm = { version = "0.10", features = ["aes"] }
rand = "0.8"
once_cell = "1.19"
parking_lot = "0.12"
bloomfilter = "1.0"
bytes = "1.5"
crossbeam-channel = "0.5"

[dev-dependencies]
proptest = "1.5"
tempfile = "3.10"
serde_json = "1.0"
criterion = "0.5"

[[bench]]
name = "kv_engine_bench"
harness = false
