[package]
name = "hightower-client"
version = "0.1.0"
edition = "2021"
authors = ["Chris Hayen <chris@shotgun.dev>"]
description = "Hightower client library"
license = "MIT"
repository = "https://github.com/chrishayen/hightower-client"
homepage = "https://github.com/chrishayen/hightower-client"
documentation = "https://docs.rs/hightower-client"
readme = "README.md"
keywords = ["wireguard", "gateway", "networking", "vpn", "hightower"]
categories = ["network-programming", "api-bindings"]
exclude = [
    "target/",
    ".git/",
    ".gitignore",
    ".claude/",
    "*.lock",
]

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hightower-wireguard = { version = "0.1.5", features = ["transport"] }
hightower-stun = "0.1.1"
hex = "0.4"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tempfile = "3"
