[package]
name = "hightower"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wgcurl"
path = "src/bin/wgcurl.rs"

[[bin]]
name = "ht"
path = "src/bin/ht.rs"

[dependencies]
hightower-client = "0.1"
hightower-stun = "0.1"
clap = { version = "4.4", features = ["derive", "env"] }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
url = "2.5"
