[package]
name = "hightower-client-lib"
version = "0.1.0"
edition = "2021"
authors = ["Chris Hayen <chris@shotgun.dev>"]
description = "Client library for Hightower gateway registration"
license = "MIT"
repository = "https://github.com/chrishayen/hightower-client-lib"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hightower-wireguard = "0.1.5"
hightower-stun = "0.1.1"
hex = "0.4"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
