[package]
name = "hightower-stun"
version = "0.1.0"
edition = "2021"

[dependencies]

[[example]]
name = "get_public_ip"
path = "examples/get_public_ip.rs"

[[example]]
name = "run_server"
path = "examples/run_server.rs"
